language: node_js
node_js:
 - "6.9.0"
 - "6.0.0"
script: 
 - npm test
 - npm run-script lint
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MEhhbGYtU2hvdCUzQWhhbGYtc2hvdC51ay8lMjFOYlRzc3hSVVdSWXRwQk1XZUYlM0FoYWxmLXNob3QudWs"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
