"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
required: ["bridge", "app_auth","hashtags","timelines","media"]
properties:
    bridge:
        type: "object"
        required: ["domain", "homeserverUrl"]
        properties:
          domain:
            type: "string"
          homeserverUrl:
            type: "string"
          database_file:
            type: "string"
    app_auth:
        type: "object"
        required: ["consumer_key", "consumer_secret"]
        properties:
          consumer_key:
            type: "string"
          consumer_secret:
            type: "string"
    hashtags:
        type: "object"
        required: ["enable"]
        properties:
          enable:
            type: "boolean"
          poll_if_empty:
            type: "boolean"
          single_account_fallback:
            type: "boolean"
    timelines:
        type: "object"
        required: ["enable"]
        properties:
          enable:
            type: "boolean"
          poll_if_empty:
            type: "boolean"
          single_account_fallback:
            type: "boolean"
    media:
        type: "object"
        required: ["enable_download","enable_profile_images"]
        properties:
          enable_download:
            type: "boolean"
          enable_profile_images:
            type: "boolean"
    logging:
        type: "object"
        properties:
          file:
            type: "string"
          size:
            type: "string"
          count:
            type: "integer"
          compress:
            type: "boolean"
          level:
            type: "string"
    provisioning:
        type: "object"
        required: ["enable"]
        properties:
            enable:
              type: "boolean"
            required_power_level:
              type: "integer"
    metrics:
      type: "object"
      properties:
        enable:
          type: "boolean"
    formatting:
      type: "object"
      properties:
        user_displayname:
          type: "string"
