bridge:
  domain: localhost
  homeserverUrl: http://localhost:8008
  database_file: twitter.db

app_auth: # Get these from twitter by creating an application through the API site.
  consumer_key: BLAHBLAHBLAH
  consumer_secret: BLAHBLAHBLAH

hashtags:
  enable: true # Enable processing hashtag rooms and creating new ones
  poll_if_empty: false # Poll the timeline, even if the room is empty
  single_account_fallback: false # Use a single account if a bunch of new members join.

timelines:
  enable: true # Enable processing timeline rooms and creating new ones
  poll_if_empty: false # Poll the timeline, even if the room is empty
  single_account_fallback: false # Use a single account if a bunch of new members join.

rooms:
  member_join_threshold: 15 # Amount of members allowed to join per minute

media:
  enable_download: true # Enable download of media attached to tweets
  enable_profile_images: true # Enable download of profile images

logging:
  file: logs/twitter-bridge.log #Filepath of the log file.
  console: true
  compress: false # Compress the files in GZip format?
  level: verbose # One of error,warn,info,verbose,silly,silent
  rotate:
    daily: true # Should the log file be rotated each day.
    size: 50m # Maximum size of a log file before it's rotated.
    count: 3 # How many log files should be kept
      # yy: Last two digits of the year.
      # yyyy: Full year.
      # M: The month.
      # MM: The zero padded month.
      # d: The day.
      # dd: The zero padded day.
      # H: The hour.
      # HH: The zero padded hour.
      # m: The minute.
      # mm: The zero padded minute.
      # ddd: The weekday (Mon, Tue, ..., Sun).
    datePattern: "yyyy-MM-dd" # Date pattern to be used with daily.
  file:
  rotate:
    date: false
    size: false
    count: 1
    datePattern:  # Date pattern for files split by date
  compress:
  level:

provisioning: # Provisioning system for scalar-enabled clients such as Riot.
  enable: true # Enable the system. This does not disable existing registered rooms.
  required_power_level: 50 # Required power level to bridge to rooms. Defaults to 50.

metrics: # Expose prometheus-style bridge statistics from '/metrics'
  enable: true

formatting:
  # Set the user's displayname to the specified format. Common options are
  # %name %id_str %screen_name
  # though you may use any top level field from https://dev.twitter.com/overview/api/users
  user_displayname: "%name (@%screen_name)"
