bridge:
  domain: localhost
  homeserverUrl: http://localhost:8008
  database_file: twitter.db

app_auth: # Get these from twitter by creating an application through the API site.
  consumer_key: BLAHBLAHBLAH
  consumer_secret: BLAHBLAHBLAH

hashtags:
  enable: true # Enable processing hashtag rooms and creating new ones
  admin_only: false # NOT USED. Only an admin listed can create these rooms.

timelines:
  enable: true # Enable processing timeline rooms and creating new ones
  # NOT CURRENTLY IN USE
  # admin_only: false. Only an admin listed can create these rooms.

# NOT CURRENTLY IN USE.
# admins: List of users that can modify the bridge.
#  - @test:localhost

media:
  enable_download: true # Enable download of media attached to tweets
  enable_profile_images: true # Enable download of profile images

logging:
  file: logs/twitter-bridge.log #Filepath of the current log file. (old ones are rotated.)
  size: 50m # Maximum size (m,k,b) of a log file before it is rotated.
  count: 3 # Maximum number of files to keep before old files are deleted.
  compress: false # Compress the files in GZip format?
  level: verbose # One of error,warn,info,verbose,silly,silent

provisioning: # Provisioning system for scalar-enabled clients such as Riot.
  enable: true # Enable the system. This does not disable existing registered rooms.
  required_power_level: 50 # Required power level to bridge to rooms. Defaults to 50.

metrics: # Expose prometheus-style bridge statistics from '/metrics'
  enable: true

formatting:
  # Set the user's displayname to the specified format. Common options are
  # %name %id_str %screen_name
  # though you may use any top level field from https://dev.twitter.com/overview/api/users
  user_displayname: "%name (@%screen_name)"
